CREATE TABLE Reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reviewName VARCHAR(255) NOT NULL,
  pieceName VARCHAR(255) NOT NULL,
  reviewText TEXT NOT NULL,
  userRating INT NOT NULL,
  tags VARCHAR(255),
  likes INT DEFAULT 0,
  creatorId BIGINT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (creatorId) REFERENCES Users(id)
);
